---
title: "ReadMe"
output: html_document
---

# Introduction and project outline

Getting and Cleaning Data Course Project

The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit: 1) a tidy data set as described below, 2) a link to a Github repository with your script for performing the analysis, and 3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.

One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

Here are the data for the project:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

You should create one R script called run_analysis.R that does the following.

Merges the training and the test sets to create one data set.
Extracts only the measurements on the mean and standard deviation for each measurement.
Uses descriptive activity names to name the activities in the data set
Appropriately labels the data set with descriptive variable names.
From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

# Run_Analysis: (please read run_Analysis File along side)


## Step 0: Download and load Data
### 0.1 Download the data and unzip it into wd
### 0.2 Read subject ids activity labels 
### 0.4 Load train and test data sets

## Step 1: Merge the train and test datasets
### 1.1: Set subject IDS
### 1.2 Set labels
### 1.3 Bind tain and test data
### 1.4 Merge colums

## Step 2: Extract mean() and std()
### 2.1 From features.txt get names of all features that contain mean() and std()
### 2.2 from names associate feature code and match to column name in DT.ALL
### 2.3 Set subject and activity labels as keys
### 2.4 Append the feature code (These are what we are extracting)

## Step 3: USe descriptive names for activities in data set
### 3.1 Acticity_labels.txt contain the names
### 3.2 Set names

## Step 4: Label data sett Appropriatly 
### 4.1 Merge DT.activity.names with DT.All by activity.label

## Step 5: create second data set
### 5.1 select feautres based on if feautre was measure of 

#### 'frequency or time' 

#### 'Accelerometer or Gyroscope'

#### 'Gravity or Body'

#### 'mean or std'

#### 'jerk or mag'

#### and spatial measurements

### 5.2 Set keys

### 5.3 Write to file 





